### ISSUE TITLE
It doesn't seem to work as well when I do it

### ISSUE THREAD

**Issue by kzhao94** [alualu628628/Husky_Simulation#2]
hi～ thank you for sharing this project.
I followed these steps, it didn't seem to work normally.
some error is displaying in terminals:
1.roslaunch loam_velodyne loam_velodyne.launch
`[ERROR] [1587871780.768998744]: Lookup would require extrapolation into the past.  Requested time 1410.430000000 but the earliest data is at time 1451.620000000, when looking up transform from frame [lidar_sensor] to frame [odom]
`
2.roslaunch topo_confidence_map mapping.launch
`[ INFO] [1587872094.246802712]: Initial the first goal: remain confidence computed time is: [-331].
updating node totalvalue: 
****remove node number: 0
****remain wide node number: 0
remain unvisited nodes are 0
`
3.roslaunch husky_navigation_goals send_goal.launch 
`[ INFO] [1587872052.014035066]: Waiting for the move_base action server to come up
`

**Comment by alualu628628** [comment]
[ERROR] from LOAM does not matter. First, please make sure that the LOAM ros node is started before the topo_confidence_map ros node, or the  topo_confidence_map ros node will not receive data and shut down automatically. In addition, it is welcomed to revise the parameters listed in mapping.launch for your own test gazebo scene. Finally, I suggest to update and download the latest version of our system to solve issue.
