### ISSUE TITLE
Why the husky works step-by-step

### ISSUE THREAD

**Issue by wangxuexiFINR** [alualu628628/Husky_Simulation#4]
https://user-images.githubusercontent.com/41510104/115572464-7e51af80-a2f2-11eb-833a-4d3c907a80b5.mp4

As you see, the husky works 'step-by-step' , which is not smooth, but i don't why

thank you!

**Comment by alualu628628** [comment]
I think there are two possible reasons:
1. The refresh rate of Gazebo simulation is low
2. The system load is heavy for the running platform, it seems better to close some mapping functions. However, in this version, I have not separated each blocks into independent nodes.
