### ISSUE TITLE
Husky does not move

### ISSUE THREAD

**Issue by wikiahuang** [alualu628628/Husky_Simulation#5]
Hello, thanks for your excellent work!
I don't know why my husky doesn't move after running this project following your steps.Do I need to execute some additional commands？

![github 1](https://user-images.githubusercontent.com/111863459/220238802-d3ee87ed-e9df-49f2-9fd2-ba6ad746f84b.png)

**Comment by alualu628628** [comment]
I did not find the point clouds produced by velydone LiDAR from your given img. Therefore, I would guess that the robot does not receive the realtime lidar scanning data, so it would not do any action. Please make sure all package is installed successfully.

**Comment by alualu628628** [comment]
In addition,  it is different for velydone lidar package in the indigo version and the melodic version. This is why we have to put velydone lidar package into our packages.
